# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gravtastic}
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Lloyd"]
  s.date = %q{2010-10-11}
  s.description = %q{Add Gravatars to your Rubies/Rails!}
  s.email = %q{christopher.lloyd@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/gravtastic.rb",
     "spec/gravtastic_integration_spec.rb",
     "spec/gravtastic_spec.rb",
     "spec/helper.rb"
  ]
  s.homepage = %q{http://github.com/chrislloyd/gravtastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{gravtastic}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby/Gravatar}
  s.test_files = [
    "spec/gravtastic_integration_spec.rb",
     "spec/gravtastic_spec.rb",
     "spec/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

